Repository autobrr/autobrr.com, pull requests merged in 2023-09, with the labels that each got.

#119 fix(faq): add info about changing the username
  docs/faqs.md
Labels: documentation

#122 fix: style fixes and enhancements
  docusaurus.config.js
  package.json
  pnpm-lock.yaml
  src/css/custom.css
  src/pages/index.js
  src/theme/Details/styles.module.css
  static/img/autobrr-front.png
  static/img/front-dark.png
  static/img/front-light.png
Labels: enhancement

#123 enhancement: separate reverse proxy examples, minor styling fixes
  docs/installation/docker.md
  docs/installation/linux.md
  docs/installation/reverse-proxy/caddy.md
  docs/installation/reverse-proxy/nginx.md
  docs/installation/reverse-proxy/swag.md
  docs/installation/reverse-proxy/traefik.md
  docs/installation/supplementary/postgresql.md
  docs/installation/supplementary/transfer-installation.md
  docs/installation/windows.md
  sidebars.js
  src/css/custom.css
Labels: documentation, enhancement
