Repository autobrr/autobrr.com, pull requests merged in 2024-12, with the labels that each got.

#232 docs(traefik): add subfolder configuration example
  docs/installation/reverse-proxy/traefik.md
Labels: documentation, enhancement

#237 feat(changelog) remove commit hash references
  .github/workflows/update_release_notes.yml
  blog/2024-04-16-v1.41.0/index.md
  blog/2024-05-09-v1.42.0/index.md
  blog/2024-06-18-v1.43.0/index.md
  blog/2024-07-20-v1.44.0/index.md
  blog/2024-08-25-v1.45.0/index.md
  blog/2024-09-12-v1.46.0/index.md
  blog/2024-09-13-v1.46.1/index.md
  blog/2024-10-06-v1.47.0/index.md
  blog/2024-10-07-v1.47.1/index.md
  blog/2024-10-20-v1.48.0/index.md
  blog/2024-11-06-v1.49.0/index.md
  blog/2024-11-09-v1.50.0/index.md
  blog/2024-11-24-v1.51.0/index.md
  blog/2024-11-25-v1.51.1/index.md
  blog/2024-12-01-v1.52.0/index.md
  blog/2024-12-08-v1.53.0/index.md
  blog/2024-12-11-v1.53.1/index.md
  update_release_notes.py
Labels: documentation

#235 docs: warn about broken sqlite to postgres conversion
  docs/installation/supplementary/postgresql.md
Labels: bug, documentation

#238 docs: update indexers and freeleech support lists
  snippets/freeleech.mdx
  snippets/indexers.mdx
Labels: documentation

#239 docs(filters): add dynamic freeleech table
  docs/filters/freeleech.md
Labels: documentation, enhancement

#240 docs(filters): add announce type
  docs/filters/basics.md
Labels: documentation

#242 docs: update indexers and freeleech support lists
  snippets/freeleech.mdx
  snippets/indexers.mdx
Labels: documentation

#246 docs: update indexers and freeleech support lists
  snippets/freeleech.mdx
Labels: documentation

#247 docs: add authentication section
  docs/configuration/authentication.md
  sidebars.js
Labels: documentation
